version: 2
jobs:
  check:
    docker:
    - image: circleci/python:3.6-browsers
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run check
        command: |
          . venv/bin/activate
          python check_script.py

workflows:
  version: 2
  commit-workflow:
    jobs:
      - check
  scheduled-workflow:
    triggers:
      - schedule:
          cron: 0 12,23 * * *
          filters:
            branches:
              only: master
    jobs:
      - check